services:
  backend:
    build:
      context: ./
      dockerfile: build/Dockerfile
    ports:
      - 8080:8080
    networks:
      - comms
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - comms
    depends_on:
      - backend

networks:
  comms: