services:
  backend:
    tty: true
    build: .
    ports:
      - 8080:8080
    networks:
      - comms
    volumes:
      - .:/usr/src/notifications
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - comms
    depends_on:
      - backend

networks:
  comms: